### ISSUE TITLE
5x Sharing Cart -- Course not usable any more

### ISSUE THREAD

**Issue by white-rabbit07** [donhinkelman/moodle-block_sharing_cart#86] opened 2021-02-04 20:06 UTC
Hi.
I wanted to add a Sharing Cart to my course ... and it took a while until the block appeared. Obviously I clicked on "Add block ..." some more times. Now the course is not usable any more. I get this:

![sharing_cart](https://user-images.githubusercontent.com/17621425/106949005-bd795700-672c-11eb-80aa-b66b43c13aac.png)
The webpage can't load any more ... what's wrong there or how to solve it?
Thanks.

**Comment by donhinkelman** [comment] 2021-02-05 00:37
Thank you for reporting a problem. In order to fix an issue, we need to reproduce it. So please tell me your Moodle version number, the Sharing cart version number, the browser you are using, the Moodle theme you are using and the any other modifications to your site that may be related.  Usually the problem is the theme, because the Sharing Cart works with standard themes.

**Comment by white-rabbit07** [comment] 2021-02-05 12:57
Hi.
We use Moodle 3.8.6 (Build: 20201109) with 
Sharing Cartblock  3.8, release 172020090100
Browser: Any -- tested with FF, Chrome, Opera
Modifications: none -- Theme: Boost (default)
I think the problem was that I clicked on "sharing cart" several times ... so it was added many times to the course!?
The course can't be used any more as soon as I switch to editing mode (the sharing cart appears many times on the right then...)

hope this helps?
Greetings.

**Comment by donhinkelman** [comment] 2021-04-09 21:47
Thanks for reporting all the helpful details and sorry for my late reply. Could you tell me if this problem is still an issue after upgrading to Sharing Cart 3.9, release 3?

**Comment by donhinkelman** [comment] 2021-05-18 00:37
Hi Johnny, I am wondering if this issue is urgent. What do you think? Can you work on it or close it if it has been fixed. Also, if you think it is timely, I would like to announce Sharing Cart 3.10 on the moodle.org plugins database and begin testing it on Moodle 3.11.

**Comment by white-rabbit07** [comment] 2021-05-18 05:33
Hi. As our moodle runs in a school I just updated Sharing Cart without forcing the potential bug again .... so I can't tell you if the problem still exists. Last time the course was unusable ... that's too critical at the moment.

**Comment by donhinkelman** [comment] 2021-05-18 06:42
I see. Thanks for trying. I see your problem.

**Comment by johnnypraxis** [comment] 2021-05-21 07:29
Hi Don
I haven't had time to test the issue. However it doesn't seem like a critical issue but it's something we need to test. Therefore I'll leave this issue open until one of my team members has the time to look into it.
I will create a Moodle 3.10 branch today and push the files :-)

**Comment by donhinkelman** [comment] 2022-02-08 15:14
Hi Johnny, any information on testing of this one?

**Comment by johnnypraxis** [comment] 2022-02-21 07:50
Hi Don
No not yet. We got a lot of tasks at the moment and not enough hands. Feel free to test the issue.

**Comment by AraPraxis** [comment] 2023-03-22 10:15
I've looked further into this, and when it comes to Blocks in Moodle, they don't really give an optimized way of preventing this - The only way would be to delete the duplicated instances if you click more than once, but that's not be the best way to prevent this.

I've tried to describe the problem to Moodle as it's not only the sharing cart but any block that should not be added more than once to a course.
Moodle Tracker issue: https://tracker.moodle.org/browse/MDL-77710

I would like to address that the way the course breaks, for me too, is rather odd but we will hopefully have time in the future to make the sharing cart run more smoothly!

I see that we close the issue, since it's Moodle that needs their source code updated :)

**Closed** 2023-03-22 10:59 UTC
