### ISSUE TITLE
Moodle 4.0 update

### ISSUE THREAD

**Issue by AraPraxis** [donhinkelman/moodle-block_sharing_cart#130] opened 2022-09-14 12:50 UTC
Hello @donhinkelman 

We've made some few changes on the sharing cart on Moodle 4.0, which basically includes a drag and drop feature to drag activities and sections into the block region or into the basket icon that will pop up over the question mark icon.

Could you possibly push this up on Moodle Org?

Best regard,
Anders Rasmussen

Trainee
Praxis Forlag A/S

**Comment by donhinkelman** [comment] 2022-10-10 06:47
Hi Anders, thanks for working on the Sharing Cart for 4.0. Actually, I understand from Frederik, that the drag-and-drop feature (replacing the basket icon) was implemented previously. Is that what you are talking about? Or something different? Or a revision of what Frederik did last month?  This drag-and-drop feature is nice direction, but it has caused confusion among users used to the old way of clicking on the basket icon. Does this new version lessen the confusion? Could you describe what is different?  Unfortunately, it is difficult to directly contact the thousands of Sharing Cart downloaders to warn them of significant changes.

**Comment by AraPraxis** [comment] 2022-10-10 07:25
Hello Donhinkelman,

This is an older version than the one that Frederik made, but he did notice me of the confusion.
I see that I've forgotten to make a pull request to your branch, with the changes I've made and gotten approved, just last week.

In the previous PR, I accidentally set the standard to drag and drop, but as the new PR explains, it only works in Moodle 4.0
To lessen the confusion I've set the standard back to 'Click to add' as it has always been, and written that 'Drag and drop' only works on 4.0

I've also added a basket icon in the footer of Moodle 4.0, when you choose to drag and drop, since the block region could be closed without us knowing. So it's still possible to add activities even if it's closed.
As a tiny difference I've also changed the spinner to a basket icon instead, which shakes with the icon.

https://github.com/donhinkelman/moodle-block_sharing_cart/pull/135

I hope this clears it up a bit!

Sincerely,
Anders Rasmussen

Trainee
Praxis Forlag A/S

**Comment by donhinkelman** [comment] 2022-10-12 15:17
Thanks, Anders, for all the changes. I appreciate that the basket icon is again default, except in 4.0. Also, I am curious about this: "As a tiny difference I've also changed the spinner to a basket icon instead, which shakes with the icon." That sounds interesting. Did you check it with any users? Do they like it?

**Comment by donhinkelman** [comment] 2023-01-21 15:41
I think this issue might be close to closing. Has anyone tested the "basket shaking icon"?

**Closed** 2023-04-18 11:11 UTC
Labels: question

**Comment by donhinkelman** [comment] 2023-04-18 11:20
Thank you, Anders, for closing this issue and checking with users about the new icon. As you may notice, after several github issues are fixed, I download a zip file and submit it to the Moodle Plugins Database, where most institutions download their custom plugins. If we get no complaints, then we can be sure the issue is really closed. :-) BTW, you should also know that the Sharing Cart is among the top ten downloaded custom blocks for Moodle, and over 10,000 institutions have used it.

**Comment by AraPraxis** [comment] 2023-04-18 11:25
No problem!
I'm glad to hear that it's getting used, and hereto that they like the features :smiley:
