### ISSUE TITLE
Duplication of block on Moodle 3.9

### ISSUE THREAD

**Issue by jonlucholmes** [donhinkelman/moodle-block_sharing_cart#77] opened 2020-11-16 14:48 UTC
Moodle version: 3.9.2+ (Build: 20201030)
Plugin version: 3.9, release 17 (Build: 2020090100)

When using the sharing cart block on Moodle 3.9, the block and buttons within it will be duplicated once content is copied into it.

1) Go into Course A, enable editing and add the sharing cart block
2) Copy a section or activity into the block
3) Go into Course B, enable editing and add the sharing cart block

Upon following these steps, two instances of the sharing cart will appear on the second course that I'm attempting to bring content into via the sharing cart.

![image](https://user-images.githubusercontent.com/9091061/99266005-3b0e8480-281a-11eb-8c30-d6ffa97e4dbd.png)

Each block is a separate instance and can be deleted individually. Likewise, the 'delete' and 'copy to course' buttons next to the copied section appear twice. Within the settings dropdown for the block instances, the bulk delete option is duplicated as well.

![image](https://user-images.githubusercontent.com/9091061/99266197-6beeb980-281a-11eb-9c8e-f53f4f488968.png)

However, deleting one of the block instances then fixes the duplication shown above.

![image](https://user-images.githubusercontent.com/9091061/99266519-bf610780-281a-11eb-8658-76a516ff67b7.png)
![image](https://user-images.githubusercontent.com/9091061/99266536-c4be5200-281a-11eb-99e3-3286700ce469.png)

**Comment by donhinkelman** [comment] 2021-04-09 21:39
Hi Jon Luc Holmes, and sorry for this late reply to your helpful post of an issue with the Sharing Cart. I wonder if you are still experiencing this issue with the latest Sharing Cart 3.9 release 3. Note that php 7.1.x or later is required.

**Comment by marxjohnson** [comment] 2022-11-11 11:12
I have attempted to reproduce this, using both `MOODLE_39_STABLE` and `master` branches of core & sharing cart. I was unable to reproduce the issue.

**Comment by frederikmillingpytlick** [comment] 2022-12-14 08:26
This issue seems fixed, if anyone is still able to recreate this issue, feel free to reopen this issue.

Closing issue

**Closed by frederikmillingpytlick** 2022-12-14 08:26 UTC
