### ISSUE TITLE
loss of configuration when copying Topics	

### ISSUE THREAD

**Issue by doiphode** [donhinkelman/moodle-block_sharing_cart#76] opened 2020-11-16 10:32 UTC
When using the sharing cart to copy entire topics, any restrictions which have been added to the topic are stripped out when it is copied into the other course area.

**Comment by abias** [comment] 2020-11-19 11:53
I think this is a duplicate of #63

**Comment by donhinkelman** [comment] 2020-11-19 13:13
Thank you, diophode, for reporting this issue. I will close this issue as a duplicate, and see if we can move on Issue #63.

**Closed by donhinkelman** 2020-11-19 13:13 UTC
