### ISSUE TITLE
Multi-Language Content filter in section name

### ISSUE THREAD

**Issue by olga0601** [donhinkelman/moodle-block_sharing_cart#157] opened 2023-03-02 08:33 UTC
When you add a Multi-Language Content filter inside section name and add the section to the sharing cart block, the sharing cart gets the multilang broken so it filters it and get nothing.
You can see the section inside the sharing cart block but it's impossible to delete it or to copy it to the course.
Only using bulk delete allows to delete this section from the cart.
When you use Multi-Language Content filter inside activity or resource name the problem doesn't appear.

For example if I give a section this  Multi-Language name:
<span lang="en" class="multilang">your_content_in English</span>
      <span lang="de" class="multilang">your_content_in_German_here</span>
and then copy the section to the sharing cart it will appear there.
When I try to delete it or copy it to the course the waiting icon appears but nothing happens.
![Untitled](https://user-images.githubusercontent.com/19852616/222374345-c27224d4-0fa5-4352-a3be-48c4c499e139.png)

**Comment by donhinkelman** [comment] 2023-03-15 08:56
Thank you olga0601 for posting this issue. I suspect this is an old but rare issue because Multi-language content filter is not commonly used. But it is important to us in Japan. I will try to replicate the error in my 4.x dev site. In the meantime, users should avoid multi-language content in section headings.

**Comment by AraPraxis** [comment] 2023-04-18 11:34
@donhinkelman

Have you had the time to test this yet? :)

**Comment by donhinkelman** [comment] 2023-04-18 11:49
Oh gosh, no. It is hard to find a site using the multi-language content filter. Let me check one possible one.

**Comment by donhinkelman** [comment] 2023-04-19 02:11
Hi Anders, I just confirmed that this problem continues. I used Sharing Cart 4.1 in a Moodle 4.0 course that uses Multi-language filters in the section titles. I can copy the section into the Sharing Cart block successfully, but when I try to copy back into an empty section in the same course, nothing happens. I click and the section is not copied and there is no error message.

This is the site: https://moodlejapan.org/.  If you make an account there, I can show you the problem. Or you can paste this sample multilanguage section title into your test site and see the problem.
<span lang="en" class="multilang">Basic Information</span><span lang="ja" class="multilang">基本情報</span>

**Comment by donhinkelman** [comment] 2023-04-19 02:15
You have to click "Edit" to see the full HTML code:  <span lang="en" class="multilang">Basic Information</span><span lang="ja" class="multilang">基本情報</span>

**Comment by frederikmillingpytlick** [comment] 2024-08-15 13:41
This should be working in the newest version, closing issue.

If not you're not able to make it work feel free to let us know :)

**Closed by frederikmillingpytlick** 2024-08-15 13:41 UTC
