### ISSUE TITLE
User unable to delete items in sharing cart

### ISSUE THREAD

**Issue by cbrherms** [donhinkelman/moodle-block_sharing_cart#173] opened 2023-09-07 10:14 UTC
I have had a user report that they are unable to delete items from their sharing cart after using it to recreate resources during our academic year start.

User does have folders with quite a few items in, but when trying to delete any item either individually or in bulk, after clicking confirm nothing happens and item is still present.

Versions:
Moodle: 4.1.5+ (build 20230818)
Sharing cart: 4.1, release 1 (build 2023032300)

**Comment by Urpokarhu1** [comment] 2023-09-12 12:44
I have run in this also in Moodle 4.1 & Sharing cart: 4.1, release 1 (build 2023032300), teacher cannot delete labels from her sharing cart at all.

**Comment by bfriesenvcc** [comment] 2023-09-14 21:51
Also experiencing this in 4.1, release 1 2023032300 on Moodle 4.1.5.
In addition to the behaviour explained above, when attempting to "cleverly" manage the files through the User private backup files area, we get an error: filereferenceproblem
![sc image](https://github.com/donhinkelman/moodle-block_sharing_cart/assets/8193384/d3cf27b7-9dff-4f16-83c7-562f7c39e354)

**Comment by donhinkelman** [comment] 2023-09-15 01:55
Thank you all for reporting this issue in Sharing Cart 4.1. I will assign it to the Praxis team (now a new name) to look into.

**Comment by frederikmillingpytlick** [comment] 2023-09-15 06:22
Hi everyone we at Moxis (new name) will have a look at this.

@donhinkelman for future issue assigning, you can just assign @mcardle and he will make sure someone from our team takes a look at it. :)

**Comment by ldgtd** [comment] 2023-09-25 12:50
Hello, same issue here on : Moodle 4.1.5 (Build: 20230814). 
Thanks in advance for your job 👍

**Comment by sharpchi** [comment] 2023-10-12 08:42
Is there any update on a fix for this. We have users also reporting this issue (M4.1.5)

**Comment by Urpokarhu1** [comment] 2023-12-04 05:55
I would like to see a fix for this

**Comment by Urpokarhu1** [comment] 2024-02-19 06:12
I would like to see this fixed

**Comment by frederikmillingpytlick** [comment] 2024-02-27 08:58
Hi @Urpokarhu1 and everyone else,

I can't seem to reproduce this issue. Do you have any step by step guide to producing this error?

**Comment by frederikmillingpytlick** [comment] 2024-08-15 13:45
The sharing cart have been completely reworked since this issue was reported & we've gotten no response, I will be closing the issue.

Feel free to let us know if the issue still persist :)

**Closed as completed by frederikmillingpytlick** 2024-08-15 13:45 UTC
