### ISSUE TITLE
Improvement: Make the UI more informative while adding items to the UI

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#13] opened 2019-03-20 14:21 UTC
Hi Don,

we've encountered this while testing the plugin for Moodle 3.6, but this also occurs at least with the previous version and is not a speciality of the 3.6 version.

**Problem**
The copying to the sharing cart takes quite some time, especially when adding a whole section with many activities and resources. In my test, I've added a section and the spinner saying "Please wait" occurred, which is fine to get to know that something happens. The problem was, that after about 5 minutes the process was not finished yet and I did not know if the process was aborted or if it was still working. Such spinners can continue spinning even if the page does not react anymore and therefore I "killed" the process by closing my browser, because I thought that the process should not take so much time.

**Proposal**
Instead of showing a spinner, I would suggest to show a progress bar and add the information how many items were processed so far (for example, 5 / 23 items are added to the sharing cart or something like that). So a user can see what happened so far and if the counter does not increase for some time, at least he can assume that the process was stuck and get an impression how far to end the whole process is.

Thanks in advance and best regards, 
Kathrin

**Comment by TubsDK** [comment] 2019-11-27 19:13
Hi Katrhin 

Tue from Praxis here. We have started helping out on the Sharing Cart plugin. Your idea is great - but I am not sure this can actually be solved. For now I have marked your report as an improvement since it not considered an actual bug.

**Comment by Mikkeljeppesen1** [comment] 2020-08-13 12:47
About the proposal to a progress bar: This is a bigger task we don't have the time to make - but if someone wants to contribute, we will look into that. 

Right now, we are trying to get faster copy/restores in sharing car. There are a lot of other issues in the tracker with the same problem. Maybe we could close this one to get a better overview? 

@

**Comment by donhinkelman** [comment] 2020-08-14 08:17
I agree this would be a nice improvement. But it is not an urgent task for us to work on. Are you saying it is better to close it, for our own motivation, and re-open it someday if we decide to work on it?

**Comment by Mikkeljeppesen1** [comment] 2020-08-14 09:41
It's better for us to close it because its a "slow sharing cart" bug and I think we have 2-3 issues already in the tracker about the plugin is being slow. 

When we test the plugin we only backup and restore about 5 activities, but we can see others try to copy about 30, and that is why the plugin is slower. Right now we are trying to make a message when you copy or restore more than 10 items its says it will take some time.

**Comment by donhinkelman** [comment] 2020-08-15 14:27
Yes, I can close it based your advice. However, I am not sure what you mean by "backup/restore about 5 activities". The Sharing Cart can only backs up one activity at a time, except when Section Copy is done. By the way, Section Copy is a new feature, only about two years old and the problem of "slow sharing cart" is about 12 years old--since the original version. The Sharing Cart has been used to backup only one activity for over ten years now, and whenever a quiz with top level categories is copied, that slows everything down. The Question Bank is designed for sharing questions, however, the more you share by putting questions into System Level or other higher level categories, the slower it gets--taking 20, 40 minutes or more to copy just one quiz. Is that the problem you are working on?

**Comment by donhinkelman** [comment] 2020-08-15 14:38
Therefore, I disagree with Kathrin's blaming the slow speed problem on Section Copy. I don't think that having many activities in a Section is the problem. I suspect that the problem is that one of those activities is a quiz. And that quiz has a huge question bank (even tens of thousands of questions) and the spinner just churns for up to an hour on just one quiz. I think Kathrin is right that in order to diagnose the problem, we need more meaningful in-process feedback during the backup/restore process. Replacing the spinner with a progress bar that tells us the problematic activity would be a good improvement.

**Comment by Mikkeljeppesen1** [comment] 2020-08-17 05:24
@donhinkelman 

1. The backup and restore problem I mentioned above, is also when you restore a folder you created in sharingcart into a course, but I agree that I don't think the sharingcart is slow, when is just an assignment or similar activities. 

2. No matter what, the spinner Kathrin84 is talking about is an improvement to the plugin

**Comment by donhinkelman** [comment] 2020-08-17 05:48
Yes, I will close it. Thank you for discussing the problem. The reason I wanted to discuss it, is because there is such a long history to this problem, and I believe we will have to make a joint effort with Moodle HQ or informing them of this issue if we do not take responsibility. Now there is significant team working on Quiz question bank problem, looking towards Moodle 4.0. I would like us join that dialogue.

**Closed by donhinkelman** 2020-08-17 05:48 UTC
Labels: enhancement
