### ISSUE TITLE
The copy of a section from one course to another one doesn't work properly.

### ISSUE THREAD

**Issue by JoseFSala** [donhinkelman/moodle-block_sharing_cart#40] opened 2020-03-19 22:45 UTC
Some of the assignments and folders of the original section do not match their copy in another course, as shown in the image.

Moodle 3.8.2+ (Build: 20200312)

Sharing Cart
block_sharing_cart

3.8, release 1
2020031500

<img width="1680" alt="Screen Shot 2020-03-19 at 22 49 15" src="https://user-images.githubusercontent.com/58363432/77121163-e1f81200-6a3a-11ea-98d2-1644b915748d.png">

**Comment by donhinkelman** [comment] 2020-03-25 19:31
Thank you, Josef. The two sections are clearly and significantly different. I will attempt to reproduce this issue.

**Comment by JoseFSala** [comment] 2020-03-25 21:11
Hi Don. This issue was hapenning to me in the previous Moodle version, 3.6.7+, as well. I used to copy each activity individually instead of a section to avoid this error. Even though it was a time consuming task, this way I was sure the copy was correctly made.

**Comment by donhinkelman** [comment] 2020-03-26 00:45
Hi Josef, it sounds like this problem might have been from the original addition of this feature. Did the issue happen the first time you used section copy?  Did section copy ever work well for you?  When was approximately the first time you remember using section copy?

**Comment by donhinkelman** [comment] 2020-03-26 02:49
<img width="616" alt="Screen Shot 2020-03-26 at 11 36 17" src="https://user-images.githubusercontent.com/12912710/77605276-dbe0c480-6f57-11ea-946e-64c6e6b5f6fd.png">
<img width="553" alt="Screen Shot 2020-03-26 at 11 35 20" src="https://user-images.githubusercontent.com/12912710/77605284-dedbb500-6f57-11ea-9d72-d06d6b7ce3f7.png">

**Comment by donhinkelman** [comment] 2020-03-26 02:51
The first screenshot shows the original section items. The second screenshot shows the items after copying to another course. Two items have disappeared in the transfer, and two items were duplicated in their place (marked in red).

**Comment by JoseFSala** [comment] 2020-03-27 16:32
Hi Don,
My answers to your questions.

Did the issue happen the first time you used section copy?
Yes.

Did section copy ever work well for you?
No.

When was approximately the first time you remember using section copy?
October 2019.

Thanks,
José Francisco Sala

**Comment by JoseFSala** [comment] 2020-03-27 16:38
I am uploading heavy video files, some of them close to 1 GB. Now Sharing Chart block is not working, and I cannot see the way of copy a single activity. This is a big problem for me.
José
<img width="1730" alt="Screen Shot 2020-03-27 at 17 25 24" src="https://user-images.githubusercontent.com/58363432/77778491-5c372080-7051-11ea-8338-52360b0ded04.png">

**Comment by JoseFSala** [comment] 2020-03-27 16:59
Don, I have uninstalled and reinstalled the sharing cart block, and the same error window shows up.
José
<img width="1730" alt="Screen Shot 2020-03-27 at 17 54 41" src="https://user-images.githubusercontent.com/58363432/77780569-7aeae680-7054-11ea-9464-bf0b0092a135.png">

**Comment by donhinkelman** [comment] 2020-03-28 02:07
Hi Josef, The section copy problem (some items not copied or duplicated) is probably different from the problem you are describing now. I have asked a programmer to look at this problem. Now the problem with the video files may be different--I don't understand the error message above. But you are trying to move 1gb files with the Sharing Cart. This will cause problems even if you use Backup/Restore because of various reasons. Your upload settings in the server may be too low. Moodle settings for upload may too low. Please check these. If you can use the Sharing Cart for smaller files, then that may be the answer. Now I assume you have installed Sharing Cart 3.8, release 2 (which was put on Moodle.org plugins two days ago).  Another suggestion is that you avoid putting video files on your Moodle courses, but instead upload them to Youtube, and paste the links on your Moodle course. This practice will help in many ways.

**Comment by JoseFSala** [comment] 2020-03-28 07:53
Hi Don,
Yes, I have installed Sharing Cart 3.8, release 2 (2020032600).

<img width="1792" alt="Screen Shot 2020-03-28 at 08 18 10" src="https://user-images.githubusercontent.com/58363432/77817729-a1009d00-70cd-11ea-82c7-249b009b3109.png">

The Moodle settings for uploading files are the server limit (site upload limit: 1 GB).

<img width="1792" alt="Screen Shot 2020-03-28 at 08 12 52" src="https://user-images.githubusercontent.com/58363432/77817799-19fff480-70ce-11ea-98c4-486423145bb7.png">

I have increased the Extra PHP memory limit from 512 MB to 4096 MB.

<img width="1792" alt="Screen Shot 2020-03-28 at 07 56 36" src="https://user-images.githubusercontent.com/58363432/77817855-7400ba00-70ce-11ea-973d-1431fe2e4797.png">

I have bulk deleted all files in the Sharing Cart block and tried to copy section «6. Ecuaciones» again, but the same undefined error showed up:

undefined - Error
<html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx/1.16.1</center> </body> </html>

<img width="1730" alt="Screen Shot 2020-03-28 at 08 17 40" src="https://user-images.githubusercontent.com/58363432/77817939-deb1f580-70ce-11ea-89ed-012cace22fa7.png">

I thank you your suggestion of avoiding to put video files on my Moodle courses, and instead uploading them to YouTube. Most of the video files should be kept private. As far as I know, there is an option to keep videos private in YouTube, but I'd prefer put them in my Moodle site, because I think it is a safer environment. In the meanwhile, I would like to help solving those Moodle errors.

By the way, my first name is not Josef. It is a compound name, José Francisco. This is the reason of using the GitHub handle «JoseFSala» (the same as my Twitter handle @JoseFSala), since my first last name is Sala. Instead of using the compound first name José Francisco, it might be used only José (Joseph in English).

Regards,
José Sala

**Comment by JoseFSala** [comment] 2020-03-30 18:29
Hi Don,

I have taken some screenshots as a complementary information for the error shown when there are heavy video files.

Regards,
José Sala

<img width="1788" alt="Screen Shot 2020-03-30 at 20 16 34" src="https://user-images.githubusercontent.com/58363432/77947920-e89d4980-72c4-11ea-8d1e-774278e611b4.png">


<img width="1788" alt="Screen Shot 2020-03-30 at 20 16 25" src="https://user-images.githubusercontent.com/58363432/77947909-e3d89580-72c4-11ea-987e-b2ada64d7ef4.png">

<img width="1788" alt="Screen Shot 2020-03-30 at 20 16 16" src="https://user-images.githubusercontent.com/58363432/77947899-df13e180-72c4-11ea-9249-36fa644b302e.png">


<img width="1788" alt="Screen Shot 2020-03-30 at 20 15 15" src="https://user-images.githubusercontent.com/58363432/77947864-d28f8900-72c4-11ea-9ac6-4eff758bfa4c.png">
<img width="1788" alt="Screen Shot 2020-03-30 at 20 15 49" src="https://user-images.githubusercontent.com/58363432/77947892-dcb18780-72c4-11ea-9f7e-d38c2da03eac.png">

**Comment by donhinkelman** [comment] 2020-03-31 10:17
Thank you Jose, I really appreciate all the screenshots, particularly the error message. I asked a programmer about it and he replied:

> "The error code is "405 Method not allowed". This does not seem to be Moodle error, but the server (nginx) error. It would help with more detail by opening inspector mode of the browser, and monitor the network when error is occured, if they can provide me the URL, method, header (and body content if any) of the request which provides this 405 error."

Since it is not a Moodle error, I will suggest you to examine your browser, URL, method, header, etc. Also since you reported that the video were sometimes over 1gb, I wonder if his server settings (such as php.ini) were causing this issue.

**Comment by ponlawat-w** [comment] 2020-04-11 03:53
Dear @donhinkelman and @JoseFSala,
After investigating the issue, the problem is caused by backing up modules which have identical names or mutual prefix in their names, at the same time.
Because previously, sharing cart stores the module with file name dervied from module name and back up time, which leads to duplication in case of module names are alike and backing them up at the same time (copy section). The problem is fixed in pull request #41 by adding module ID into file name to create uniqueness.

The picture below is from my test site, it now restores all the modules correctly:

![image](https://user-images.githubusercontent.com/15243484/79034684-52312800-7be2-11ea-9f9b-ebed8a2542c6.png)

**Comment by donhinkelman** [comment] 2020-04-11 05:46
That is great to hear you could find and solve the problem. I will check it out later.
Don

**Comment by JoseFSala** [comment] 2020-04-11 16:13
I understand this issue will be fixed in the next Sharing Cart release, isn’t it?

Thanks so much,
José Sala

**Comment by donhinkelman** [comment] 2020-04-12 01:47
Hi Jose, this fix was merged into today's new release, Sharing Cart 3.8, release 3. Thanks to Ponlawat Weerapanpisit, graduate student of engineering at Chiang Mai University, and programmer of the section copy feature. I have tested this fix and will close this issue.

**Closed by donhinkelman** 2020-04-12 01:47 UTC
